repos:
  - repo: local
    hooks:
      - id: update-requirements
        name: Update requirements.txt
        entry: python scripts/update_requirements.py
        language: system
        files: ^requirements\.in$