services:
  - type: web
    name: t2g-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/run.py
    envVars:
      - key: DASH_ENV
        value: production