services:
  - type: web
    name: t2g-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.run:server
    envVars:
      - key: DASH_ENV
        value: production